/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetobanco.View;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import projetobanco.DAO.Conexao;
import projetobanco.Model.Usuario;

/**
 *
 * @author Pedro Satoru
 */
public class JanelaSenhaSaque extends javax.swing.JFrame {
    //NOME DA JANELA ESTA ERRADO, O CORRETO SERIA SENHA SALDO
    private Usuario usuario;
  
    /**
     *
     * @param usuario
     */
    public JanelaSenhaSaque(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
    }

    /**
     *
     * @return
     */
    public JButton getBtSaldo() {
        return btSaldo;
    }

    /**
     *
     * @param btSaldo
     */
    public void setBtSaldo(JButton btSaldo) {
        this.btSaldo = btSaldo;
    }

    /**
     *
     * @return
     */
    public JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     *
     * @param jLabel1
     */
    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtSenha() {
        return txtSenha;
    }

    /**
     *
     * @param txtSenha
     */
    public void setTxtSenha(JTextField txtSenha) {
        this.txtSenha = txtSenha;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        btSaldo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Digite sua senha novamente");

        txtSenha.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        btSaldo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btSaldo.setText("Ver Saldo");
        btSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSenha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btSaldo)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btSaldo)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaldoActionPerformed
        //Verifica se a senha do usuario esta correta
        String senha= this.getTxtSenha().getText();
        Conexao conexao = new Conexao();
        try{
        Connection conn = conexao.getConnection(); // Supondo que você tenha um método para obter a conexão
        if (senha == null ? usuario.getSenha() == null : senha.equals(usuario.getSenha())){
            JanelaSaldo Js = new JanelaSaldo(this.usuario,conn);
            Js.setVisible(true);
            this.dispose();
            }
       else{
            JOptionPane.showMessageDialog(this, "Senha errada!");
            }
        }catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro de conexão ao abrir a janela de saldo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSaldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
